= Inconsistency Management
:showtitle: true

An exploration of our domain terminology, database schema, events, actions and behaviors,shared inventory definition, and duplicate item criteria led to the discovery of two inconsistencies.

* Event "A Inventory has been generated" triggered by the addition of an Item to the Inventory for the first time is stated to change the Inventory so it now reflects the presence of a new Item. Inventory in our terminology is defined as "The list of available Products in a Home," while Item (synonym for Stock) is defined as "An instance of a Product." This event and its description create a designation clash to be addressed with the already existing glossary of terms in our terminology. Additionally the naming of the event alludes to the creation of an Inventory, but the described change is the modification of an already existing Inventory. To correct this clash, the event was separated into two events:
** The "What changed" section of the "An Inventory has been generated" has been changed to "The Inventory is created and reflects the presence of the new Item." This was done to separate the creation of the Inventory from the modification of the Inventory, and to clarify that the Inventory is created as a result of the addition of an Item to the Inventory for the first time. 
** The event's function was given to the new event "A new Product has been generated," triggered by the addition of a new Item to the Inventory with no relation to an existing Product. The event would change the Inventory to now reflect the new Product description, and Item count and description.

* The Grouped-Owned Inventory model on the Shared Inventory Definition document describes how all items can be mapped as belonging to the household and multiple Members being able to add, edit, and delete items. It describes how Inventories have multiple Stock entries, and Stock entries optionally have linked Owner tags. This leads to Items having the ability to have multiple Owners, which is not reflected on the ER and table diagrams for database Item representation. The model is satisfiable with the current diagrams only when Items have one and only one Owner.
** To correct this weak conflict, the ER and table diagrams for database Item representation 
have been updated to reflect this model. The intervention came in the relation between Items and Owners, making it a many-to-many relation with total participation on both sides andcas a consequence, added a new table Owns to represent the relationship. This change now allows for an Item to be owned by multiple Owners while keeping the ability of an Owner to own multiple Items.